# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='images/book', verbose_name='商品图片'),
        ),
    ]
